# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-binding
  namespace: default
subjects:
- kind: User
  name: your-user
roleRef:
  kind: Role
  name: deployment-and-service-creator
  apiGroup: rbac.authorization.k8s.io
